name: Android APK Builder
on: [push]
env:
  ANDROID_HOME: ${{ github.workspace }}/android-sdk
  ANDROIDNDK: ${{ github.workspace }}/android-ndk-r23c
  PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:$PATH
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 阶段1：使用容器化的基础工具
    - name: Setup core tools via Docker
      run: |
        # 使用官方busybox镜像提供基础工具
        docker run --rm -v $PWD:/workspace busybox:latest \
          sh -c "unzip -v && curl --version && git --version" || {
          echo "::error::基础工具检查失败";
          exit 1;
        }
        
        # 创建必要的符号链接
        docker run --rm -v /usr:/usr busybox:latest \
          sh -c "ln -sf /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5 || true"
        
    # 阶段2：Python环境
    - uses: actions/checkout@v4
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    # 阶段3：Android工具链安装（自包含方式）
    - name: Install Android tools
      run: |
        # 下载预编译的unzip工具
        curl -L https://github.com/dsoprea/unzip-static/releases/download/6.0-26/unzip-static -o /usr/local/bin/unzip
        chmod +x /usr/local/bin/unzip
        
        # 安装Android SDK
        mkdir -p $ANDROID_HOME
        curl --retry 5 --retry-delay 10 \
          https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip \
          -o /tmp/cmdline-tools.zip
        unzip /tmp/cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        
        # 安装NDK
        curl --retry 5 --retry-delay 10 \
          https://dl.google.com/android/repository/android-ndk-r23c-linux.zip \
          -o /tmp/ndk.zip
        unzip /tmp/ndk.zip -d ${{ github.workspace }}
    # 阶段4：Buildozer安装
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install --user buildozer==1.4.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    # 阶段5：构建过程
    - name: Build APK
      run: |
        buildozer init
        echo "android.ndk_path = $ANDROIDNDK" >> buildozer.spec
        echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
        
        buildozer -v android clean
        buildozer -v android debug 2>&1 | tee build.log
        
        if ! ls bin/*.apk 1> /dev/null 2>&1; then
          echo "::error::构建失败！错误摘要："
          grep -A 20 -B 10 -i "error\|fail\|exception" build.log
          exit 1
        fi
    # 阶段6：产物收集
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          bin/*.apk
          build.log