name: Build Android APK
on: [push]
env:
  ANDROID_HOME: ${{ github.workspace }}/android-sdk
  ANDROIDNDK: ${{ github.workspace }}/android-ndk-r23c
  PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:$PATH
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 第一步：安装基础工具（包括tar）
    - name: Install essential tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          tar \  # 明确安装tar工具
          gzip \
          unzip \
          zip \
          curl \
          wget \
          git \
          make
        
    # 第二步：检出代码（使用更可靠的checkout方式）
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录
        
    # 第三步：设置Python环境
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    # 第四步：解决libtinfo依赖
    - name: Fix library dependencies
      run: |
        sudo apt-get install -y \
          libtinfo6 \
          libncurses6 \
          zlib1g-dev
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libncurses.so.6 /usr/lib/x86_64-linux-gnu/libncurses.so.5
    
    # 第五步：安装Java和构建工具
    - name: Install Java and build tools
      run: |
        sudo apt-get install -y \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          cmake \
          libffi-dev \
          libssl-dev
    
    # 第六步：设置Android SDK
    - name: Setup Android SDK
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget --tries=3 --retry-connrefused \
          https://mirrors.tuna.tsinghua.edu.cn/Android/repository/commandlinetools-linux-10406996_latest.zip \
          -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0"
    
    # 第七步：设置Android NDK
    - name: Setup Android NDK
      run: |
        wget --tries=3 --retry-connrefused \
          https://dl.google.com/android/repository/android-ndk-r23c-linux.zip \
          -O ndk.zip
        unzip ndk.zip
        mv android-ndk-r23c $ANDROIDNDK
    
    # 第八步：安装Buildozer
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install --user buildozer==1.4.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    # 第九步：构建APK
    - name: Build APK
      run: |
        buildozer -v android clean
        buildozer -v android debug 2>&1 | tee build.log
        
        if ! ls bin/*.apk 1> /dev/null 2>&1; then
          echo "::error::APK build failed!"
          grep -A 30 -B 10 -i "error\|fail\|exception" build.log || cat build.log
          exit 1
        fi
    
    # 第十步：上传产物
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        
    - name: Upload build log
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log